jenkinsci/cloudbees-folder-plugin

src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
[JENKINS-28243](https://issues.jenkins-ci.org/browse/JENKINS-28243)
@reviewbybees
=> [JENKINS-28243] Fix display of permissions

pom.xml
=> mvn tidy:pom && reformat indentation

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/RelocationAction.java
And enabled FindBugs xml output so Jenkins can pick it up
@reviewbybees
=> Fixed findbugs issues

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java
=> ComputedFolder.addTrigger

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
[JENKINS-31129](https://issues.jenkins-ci.org/browse/JENKINS-31129)
@reviewbybees esp. @stephenc
=> [JENKINS-31129] Call scheduleBuild only after doConfigSubmit, not any save

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
=> More informative IllegalStateException

src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/configure-details.jelly
=> Rearrange configuration; credentials first for organization folders

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
`TopLevelItem` extends `Describable`.
@reviewbybees
=> Delete misleading comment

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/Messages.properties, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Because this class overrides `getActions()`, mutation method broke.
@reviewbybees
=> Allow Actions to be added/removed

src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java
See Javadoc for explanation.
@reviewbybees
=> SecurityContextHolder antipattern

src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java
Implements https://github.com/jenkinsci/jenkins/pull/1395 for folders.
@reviewbybees esp. @stephenc & @recena
=> Call hasCreatePermission, as Items.all does

pom.xml, src/main/resources/index.jelly
@reviewbybees specially @rtyler and @daniel-beck
=> Display names has been changed

src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
[JENKINS-25240](https://issues.jenkins-ci.org/browse/JENKINS-25240)
@reviewbybees
=> [JENKINS-25240] Do not delete branch projects with running builds

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
Needed to do https://github.com/jenkinsci/github-branch-source-plugin/pull/35 properly.
@reviewbybees
=> [JENKINS-33815] Fixing FolderComputation to properly handle AbortException

src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
[JENKINS-25240](https://issues.jenkins-ci.org/browse/JENKINS-25240), again.
@reviewbybees
=> [JENKINS-25240] Need to consider even nested jobs for purposes of checking running builds

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
Minimal solution of [JENKINS-33817](https://issues.jenkins-ci.org/browse/JENKINS-33817), sufficient for diagnosing recomputation bugs. For now, no UI option to enable, UI browsing of old logs, or smart retention policy (like saving only logs that orphaned children).
@reviewbybees
=> [JENKINS-33817] Option to save backup copies of computation log

src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
A bug that was technically introduced in #44 but made much more likely in #46.
@reviewbybees
=> [JENKINS-25240] IllegalStateException from a list iterator

src/main/java/com/cloudbees/hudson/plugins/folder/FolderAddFilter.java
Downstream of https://github.com/jenkinsci/jenkins/pull/2208.
@reviewbybees esp. @recena, @oleg-nenashev
=> [JENKINS-33972] View.doCategories renamed to doItemCategories

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/tasks-top-extra.jelly
I found this bug when I was working here https://github.com/jenkinsci/cloudbees-folder-plugin/pull/58
@reviewbybees
=> Wrong paths (hardcoded). 

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
[JENKINS-34200](https://issues.jenkins-ci.org/browse/JENKINS-34200)
@reviewbybees
=> [JENKINS-34200] Redirect to indexing log after creating or editing a ComputedFolder

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
[JENKINS-33819](https://issues.jenkins-ci.org/browse/JENKINS-33819)
@reviewbybees
=> [JENKINS-33819] New API to set the OrphanedItemStrategy field

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/main/resources/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider/FolderCredentialsProperty/config.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider/help.groovy
@reviewbybees
Fix the credentials-2.0 style of store actions and other misc tidy-up for the ew credentials 2.0 api
=> Upgrade to credentials-2.0

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
[JENKINS-34939](https://issues.jenkins-ci.org/browse/JENKINS-34939)
@reviewbybees
=> [JENKINS-34939] Hold the lock on this folder only while deleting itself, not its children

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Cf. https://github.com/jenkinsci/branch-api-plugin/pull/35.
@reviewbybees
=> [JENKINS-32178] Noting why you should not override getUrlChildPrefix

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
=> [FIXED JENKINS-36160] The credentials provider was not considering the folder as an itemgroup when accessed as an Item

src/main/resources/com/cloudbees/hudson/plugins/folder/relocate/RelocationAction/index.jelly
[JENKINS-37941](https://issues.jenkins-ci.org/browse/JENKINS-37941)
@reviewbybees esp @amuniz (who actually found the issue)
=> [FIXED JENKINS-37941] add norefresh=true in index.jelly

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
=> Reject attempts to call ChildObserver.created with something that is not in fact a child of this folder

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
See [JENKINS-40440](https://issues.jenkins-ci.org/browse/JENKINS-40440)
@reviewbybees
=> [FIXED JENKINS-40440] Computed folder should not redirect to computation if not buildable

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
=> Add some default content when the events log is empty

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
[JENKINS-41370](https://issues.jenkins-ci.org/browse/JENKINS-41370)
- Fix test failing for 2.32.1 version (functionally there is no problem).
- Bump parent POM and jenkins test harness versions.
@reviewbybees @stephenc
=> [JENKINS-41370] Fix PCT for 2.32.1

src/main/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreams.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreamsTest.java
See [JENKINS-42151](https://issues.jenkins-ci.org/browse/JENKINS-42151)
@reviewbybees 
(more PRs to follow downstream)
=> [JENKINS-42151] FolderComputation.createEventsListener() should be thread safe

src/main/resources/com/cloudbees/hudson/plugins/folder/computed/FolderComputation/console.properties, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/FolderComputation/events.properties
See [JENKINS-42146](https://issues.jenkins-ci.org/browse/JENKINS-42146)
@reviewbybees
=> [FIXED JENKINS-42146] Added the missing i18n bundle keys

src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/tasks-top-extra.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/tasks-top-extra.properties, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/FolderComputation/events.jelly
See [JENKINS-41416](https://issues.jenkins-ci.org/browse/JENKINS-41416)
@reviewbybees 
Menu for an organization folder:
Menu for a repository in an organization folder:
Menu for a standalone multibranch pipeline
=> [FIXED JENKINS-41416] Fold the submenu into the main menu

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ChildObserver.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See [JENKINS-42511](https://issues.jenkins-ci.org/browse/JENKINS-42511)
@reviewbybees
=> [JENKINS-42511] Correct ComputedFolder API to include blocking behaviour for concurrent events and computations

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See [JENKINS-35112](https://issues.jenkins-ci.org/browse/JENKINS-35112)
@reviewbybees
=> [FIXED JENKINS-35112] Interrupt the computation when deleting

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/ItemDeletion.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/resources/com/cloudbees/hudson/plugins/folder/Messages.properties
See [JENKINS-35112](https://issues.jenkins-ci.org/browse/JENKINS-35112) also https://github.com/jenkinsci/jenkins/pull/2789
@reviewbybees
=> [JENKINS-35112] Re-implement based on JENKINS-35160 impl in core

src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java
See [JENKINS-43424](https://issues.jenkins-ci.org/browse/JENKINS-43424)
@reviewbybees
=> [FIXED JENKINS-43424] Introduce entropy into the periodic folder trigger for short intervals

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderProperty.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderIcon.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/TransientFolderActionFactory.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderCron.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/OrphanedItemStrategy.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PseudoRun.java, src/main/java/com/cloudbees/hudson/plugins/folder/health/FolderHealthMetricDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/DefaultRelocationUI.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/ItemGroupModifier.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/RelocationUI.java, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/FolderComputation/consoleFull.jelly
See [JDK-8170447](https://bugs.openjdk.java.net/browse/JDK-8170447), if this build passes then the JDK bug is the culprit
@reviewbybees
=> [JDK-8170447] This is the only {@link} to an annotation I could find

src/main/resources/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy/config.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger/config.jelly
See [JENKINS-45823](https://issues.jenkins-ci.org/browse/JENKINS-45823)
@reviewbybees
=> [FIXED JENKINS-45823] Fix the defaulting of jelly form values

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
See [JENKINS-43518](https://issues.jenkins-ci.org/browse/JENKINS-43518)
@reviewbybees
=> [FIXED JENKINS-43518] Missing doStop method preventing abort from console log

pom.xml, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
Mainly here to pick up https://github.com/jenkinsci/plugin-pom/pull/90 and thus https://github.com/jenkinsci/jenkins-test-harness/pull/81 to allow `FolderCredentialsProviderTest` to run against https://github.com/jenkinsci/jenkins/pull/3120.
@reviewbybees
=> POM updates

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ThrottleComputationQueueTaskDispatcher.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ThrottleComputationQueueTaskDispatcherTest.java
[JENKINS-47438](https://issues.jenkins-ci.org/browse/JENKINS-47438)
@reviewbybees
=> [FIXED JENKINS-47438] Keep track of recent approvals to prevent race conditions

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Same problem and fix as [JENKINS-17401](https://issues.jenkins-ci.org/browse/JENKINS-17401).
See also jenkinsci/jenkins#3289 which would allow this code to be deleted eventually.
@reviewbybees
=> Don't show nested view when clicking apply to rename a folder

README.md, pom.xml
Wiki is now readonly so need to move the docs and releases to github
@fcojfernandez
=> Moved documentation from wiki to GitHub

.mvn/extensions.xml, .mvn/maven.config, pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolder.java, src/main/resources/com/cloudbees/hudson/plugins/folder/Messages.properties, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/Messages.properties, src/main/resources/com/cloudbees/hudson/plugins/folder/views/Messages.properties
Migrating to the newest pom and removing illegal access should unblock #127 
* ...
@fcojfernandez
=> Update to the latest pom and fix illegal access

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreamsTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandlerTest.java
Minor refactoring to fix some deprecation warnings
* N/A: Just internal
@fcojfernandez
=> Minor refactoring to fix some deprecation warnings

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly
See [JENKINS-66148](https://issues.jenkins-ci.org/browse/JENKINS-66148).
Related to https://github.com/jenkinsci/github-branch-source-plugin/pull/443
* ...
=> Fix to use the icon element in folder title

.github/CODEOWNERS
=> add a CODEOWNERS file

.github/CODEOWNERS, .github/dependabot.yml, .github/release-drafter.yml, .github/workflows/cd.yaml, .mvn/maven.config, pom.xml
=> Enable JEP-229 CD

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderJobQueueDecisionHandler.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java
* introduced diamond operator, 
* use try with resources, 
* minor improvements
* Internal
=> introduced diamond operator, use try with resources, minor improvements

pom.xml
=> Use final 2.361.x dep versions

Jenkinsfile, pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
=> Update baseline, POM

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
Fixing deprecation warnings; dealing with some old TODOs; deleting interface implementation methods which were subsequently given default implementations in core matching their implementation here.
=> Cleanup of `ComputedFolder`

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/ItemDeletion.java
A bit of cleanup from https://github.com/jenkinsci/jenkins/pull/2789 + https://github.com/jenkinsci/cloudbees-folder-plugin/pull/95; as seen in https://github.com/jenkinsci/cloudbees-folder-plugin/pull/112/commits/cdf73702a8bef58b5c2cef1d05e3b4ce823b6494, a lot more is needed.
=> Use `Tasks.getItemOf`

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderIcon.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/DeletingChildrenException.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreams.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/java/com/cloudbees/hudson/plugins/folder/health/FolderHealthMetric.java, src/main/java/com/cloudbees/hudson/plugins/folder/health/FolderHealthMetricDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/DefaultRelocationUI.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/ItemGroupModifier.java, src/main/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreamsTest.java
Fixes various IDE warnings. Each change is a separate commit to ease reviewing. If any particular commit is unwanted, please just revert it and keep the others.
`mvn clean verify`
=> Miscellaneous code cleanup

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Downstream of https://github.com/jenkinsci/jenkins/pull/8902, amending https://github.com/jenkinsci/cloudbees-folder-plugin/pull/82.
=> [JENKINS-72613] `ItemGroup.getItemName` override

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
This is a re-file of #372 with extra fixes based on PCT test failures observed internally. Should go through a BOM build for extra sanity testing.
* ...
=> [JENKINS-72613] ItemGroup.getItemName override & refactor, take 2

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderProperty.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandler.java, src/main/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
Deprecations, tech debt, copied code that can now use core APIs, etc. #101, #114, https://github.com/jenkinsci/jenkins/pull/4848
=> Assorted cleanups

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
https://github.com/jenkinsci/jenkins/pull/9311
=> Use Java 7 versions of `GZIPInputStream` and `GZIPOutputStream`

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java
Untested, but a similar change was made in https://github.com/jenkinsci/workflow-job-plugin/pull/411 without any issues.
=> Clean up after jenkinsci/jenkins#9150

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/tasks-new.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/tasks-top.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/Folder/tasks-create.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/PseudoRun/sidepanel.jelly
=> Migrate to EE 9 in Jelly views

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
=> `FolderComputation` implements `FullyNamedModelObject`
