src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java
Don't want to bump the core version of Jenkins just yet, so using reflection for now.
The use of reflection should not be a performance risk as the New Item page is not rendered
heavily, and in any case reflection gets inlined well by the JVM
@reviewbybees
=> Add support for the `TopLevelItemDescriptor.isApplicableIn(ItemGroup)` method in 1.607+

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java
Without this you get a long ugly stack trace during startup if `credentials` is disabled. With the fix you get just
```
… hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate optional component com.cloudbees.hudson.plugins.folder.properties.FolderCredentialsProvider$FolderCredentialsProperty$DescriptorImpl; skipping
```
@reviewbybees esp. @daniel-beck
=> Credentials dependency fix

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
[JENKINS-33479](https://issues.jenkins-ci.org/browse/JENKINS-33479)
@reviewbybees
=> [JENKINS-33479] NPE

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
[JENKINS-32179](https://issues.jenkins-ci.org/browse/JENKINS-32179)
Supersedes https://github.com/jenkinsci/branch-api-plugin/pull/23.
@reviewbybees
=> [JENKINS-32179] Logic error when computeChildren suggested the same child name twice during recomputation

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/sidepanel.jelly
So long as [JENKINS-32585](https://issues.jenkins-ci.org/browse/JENKINS-32585) is not implemented, a link in the sidepanel ought to be in the context menu unless we have explicitly specified `contextMenu=false`, which in this case we have not. (Anyway I find it quite convenient to use the context menu to blow away unwanted folders!)
The problem was that [here](https://github.com/jenkinsci/cloudbees-folder-plugin/blob/cd19df8330048af010056ce9c5d0920516632c4b/src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/tasks-new.jelly#L29) `view` was undefined.
@reviewbybees
=> Allow Delete Folder to appear in context menu

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Provides an alternative fix to #39 & https://github.com/jenkinsci/github-organization-folder-plugin/pull/2 (confirmed by temporarily reverting them and creating a GitHub organization), though it cannot hurt to keep those.
I considered making the override in `Folder` do the same, but [these lines](https://github.com/jenkinsci/cloudbees-folder-plugin/blob/2be74ab50054e110cae7dc158d7d18e8f04e1fa2/src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java#L134-L135) would have saved the folder anyway, unless the `owner` were not passed to the `ListView` constructor—and it cannot be passed in afterwards. Those two lines also make it hard to remove the `throws IOException` clause, though that at least could be worked around. (And it would [not be binary …
=> [JENKINS-33479] [JENKINS-33480] Avoid calling `save` from within our own constructor

src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTriggerTest.java
[JENKINS-33006](https://issues.jenkins-ci.org/browse/JENKINS-33006) seems to [always have been broken](https://github.com/jenkinsci/branch-api-plugin/commit/5e85b537e1ca543191967097fc25f00626f1e170#diff-33d257ebbba001788243c54bb248b1f6R155).
@reviewbybees esp. @stephenc
=> [JENKINS-33006] Hour-based increments were not being round-tripped correctly

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
Otherwise when diagnosing issues like that perhaps fixed in https://github.com/jenkinsci/subversion-plugin/pull/158, you see thread dumps with thread names like
Executor #-1 for master : executing jenkins.branch.MultiBranchProject$BranchIndexing@1234abcd
which is not very helpful.
@reviewbybees
=> Meaningful FolderComputation.toString

src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java
This is dead code after #48. Anyway https://github.com/jenkinsci/jenkins/pull/2192 defines a single authoritative copy of this code, which is more complete (for example it checks `ProjectNamingStrategy`).
@reviewbybees
=> Folder.doCheckJobName is obsolete

src/main/java/com/cloudbees/hudson/plugins/folder/FolderAddFilter.java
Fixes a bug identified in https://github.com/jenkinsci/jenkins/pull/2191.
Merely skipping the URI check, and applying the filtering unconditionally given a folder context, would seem simpler, but this would break code which is not part of _New Item_. For example, `SubItemFilterProperty` in `cloudbees-folders-plus` has a configuration fragment which lets you select item types to filter out. If `FolderAddFilter` were applied in `/job/folder/configure`, once you limited the folder to one item type, you would not be able to undo your decision, because the others would no longer be shown!
Tested using `SubItemFilterProperty` against both Jenkins 1.x and 2.x.
@reviewbybees esp. @recena
=> Expect FolderAddFilter to be called from View.doCategories

src/main/java/com/cloudbees/hudson/plugins/folder/FolderAddFilter.java
[JENKINS-33972](https://issues.jenkins-ci.org/browse/JENKINS-33972)
downstream of https://github.com/jenkinsci/jenkins/pull/2208
@reviewbybees especially @jglick and @oleg-nenashev
=> [JENKINS-33972] View.doCategories was renamed to View.doItemCategories

src/main/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandler.java, src/test/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandlerTest.java
1. create a job A in a folder A 
2. create a job with the same name A in another folder B 
3. Then, the move option tells you can move to:
```
Jenkins
Jenkins >> Folder A
Jenkins >> Folder B
````
But this is wrong because `Jenkins >> Folder A` is the item itself and in `Jenkins >> Folder B` there is already an item with the same name - we should cover these cases.
https://issues.jenkins-ci.org/browse/JENKINS-34306
@reviewbybees CC @jglick
=> [FIXED JENKINS-34306] When moving an item several destinations showed in the GUI are not valid

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly
https://issues.jenkins-ci.org/browse/JENKINS-32309
It's required for https://github.com/jenkinsci/ownership-plugin/pull/44
@reviewbybees
=> [FIXED JENKINS-32309] - Allow Actions to contribute summary items for folders

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Minor javadoc fixes. 
```
[ERROR] /Users/armando/Development/cloudbees-folder-plugin/src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java:109: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /Users/armando/Development/cloudbees-folder-plugin/src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java:110: error: self-closing element not allowed
[ERROR] * <b>Extending Folders UI</b><br/>
```
@reviewbybees
=> Fix javadoc errors

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
- The type erasure means that the methods are the same
- The generated bytecode only assumes `TopLevelItem` as the class: 
```
public void onRenamed(I, java.lang.String, java.lang.String) throws java.io.IOException;
Code:
0: aload_0
1: getfield      #24                 // Field items:Ljava/util/Map;
4: aload_2
5: invokeinterface #178,  2          // InterfaceMethod java/util/Map.remove:(Ljava/lang/Object;)Ljava/lang/Object;
10: pop
11: aload_0
12: getfield      #24                 // Field items:Ljava/util/Map;
15: aload_3
16: aload_1
17: invokeinterface #179,  3          // InterfaceMethod java/util/Map.put:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
22: pop
23: aload_0
24: getfield      #6                  // Field views:Ljava/util/concurrent/CopyOnWriteArrayList;
27: …
```
=> Fix IDE warnings about unimplemented `onRenamed` and `onDeleted` methods

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolder.java
Downstream of https://github.com/jenkinsci/jenkins/pull/2603
Illustrated usage of the `migrateLegacyPrimaryAllViewLocalizedName` method in a plugin. 
Here we use reflection as we do not want to force a core version bump on folders plugin.
@reviewbybees
=> [WIP JENKINS-38606 Follow-up] Ensure AllView gets migrated

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
See [JENKINS-41044](https://issues.jenkins-ci.org/browse/JENKINS-41004)
Relates to https://github.com/jenkinsci/credentials-plugin/pull/77
@reviewbybees
=> [JENKINS-41004] Do not report credentials with IDs masked by nearer folders

src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
[JENKINS-41842](https://issues.jenkins-ci.org/browse/JENKINS-41842)
Tests validating:
- No new item can be added manually to a computed folder.
- Trigger causes a computation.
@reviewbybees @stephenc
=> [JENKINS-41842] Increase test coverage for computed folder

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java
[JENKINS-42511](https://issues.jenkins-ci.org/browse/JENKINS-42511)
Fixes the problem I observed in the demo, with a once-per-minute trigger:
* cron checking Tue Mar 07 15:43:00 UTC 2017
* cron checking `WorkflowMultiBranchProject[cd]`
* scheduling `WorkflowMultiBranchProject[cd]`
* cron checking Tue Mar 07 15:44:00 UTC 2017
* cron checking `WorkflowMultiBranchProject[cd]`
* scheduling `WorkflowMultiBranchProject[cd]`
* `createExecutable` on `WorkflowMultiBranchProject[cd]`
* `createExecutable` on `WorkflowMultiBranchProject[cd]`
`FolderCron`, like the core `Cron` it was copied from, diligently reruns triggers for every discrete minute that they might have matched. If you have a trigger with a short frequency, especially one minute (the same as the period for `FolderCron`), it will …
=> [JENKINS-42511] Race condition in PeriodicFolderTrigger

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder2Test.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
[JENKINS-42593](https://issues.jenkins-ci.org/browse/JENKINS-42593)
Fixes a critical regression in #92.
@reviewbybees
=> [JENKINS-42593] Reinitialize transient lock-related fields after restart

src/test/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreamsTest.java
Test for EventOutputStream was passing incorrect parameters to helper method.
@reviewbybees @stephenc @jglick
=> Fix test not meeting expected conditions.

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PseudoRun.java, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/Messages.properties, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/PseudoRun/sidepanel.jelly
See [JENKINS-37369](https://issues.jenkins-ci.org/browse/JENKINS-37369)
@reviewbybees
Exposes the last computation information (so will only ever be either success or failure until we add computation history support)
=> [JENKINS-37369] Expose the last computation for computed folders

pom.xml, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
[JENKINS-45501](https://issues.jenkins-ci.org/browse/JENKINS-45501)
Various fixes for `pom.xml` and `FolderTest` including:
* Parent versionand test dependency bump
* Now the copy operations is performed via HttpRequest instead of trying to interact with the GUI
* Workaround for JENKINS-9774
@reviewbybees
=> [JENKINS-45501] cloudbees-folder is failing in the PCT against cores 2.32, 2.42 and 2.60

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java
- All this crazy just to match the way LogRotator in core behaves
See [JENKINS-45984](https://issues.jenkins-ci.org/browse/JENKINS-45984)
@reviewbybees
=> [FIXED JENKINS-45984] Fix the crazy logic where 0 was semantically equivalent to 'empty' but actually wasn't

pom.xml
#107 by @fcojfernandez was not in fact correct. Easily seen from `hpi:run` after viewing the index page of a folder:
```
java.lang.IllegalAccessError: tried to access method org.jenkins.ui.icon.IconSet.getIconByClassSpec(Ljava/lang/String;)Lorg/jenkins/ui/icon/Icon; from class com.cloudbees.hudson.plugins.folder.FolderIcon
at com.cloudbees.hudson.plugins.folder.FolderIcon.iconClassNameImageOf(FolderIcon.java:80)
```
Cf. https://github.com/jenkinsci/plugin-pom/pull/72. `getIconByClassSpec` changed signature in 2.0.2, incompatibly by reverting an incompatible change in 1.0.5. Core still bundles `icon-set:1.0.5` with the `Object` signature. There is a 2.x plugin with an incompatible signature for some reason. Since `FolderIcon` actually has to compile against one or the other, it needs to …
=> [JENKINS-46933] Fix icon-shim dependency the hard way

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderCron.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ThrottleComputationQueueTaskDispatcher.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandler.java, src/test/java/com/cloudbees/hudson/plugins/folder/relocate/StandardHandlerTest.java
[JENKINS-40612](https://issues.jenkins-ci.org/browse/JENKINS-40612)
@reviewbybees
=> [JENKINS-40612] More efficient idiom for hasValidDestination

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolderTest.java, src/test/resources/com/cloudbees/hudson/plugins/folder/views/DefaultFolderViewHolderTest/oldData/jobs/d/config.xml
[JENKINS-47416](https://issues.jenkins-ci.org/browse/JENKINS-47416)
Pending https://github.com/jenkinsci/jenkins/pull/3088, correct a regression in #112 of a sort; the exception was already being thrown as of #79, but swallowed.
@reviewbybees
=> [JENKINS-47416] Use a patched copy of the core API for now

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
This method is deprecated. See quote:
"This method has always returned a time in milliseconds, when various
callers incorrectly assumed seconds. And this spread through the
codebase. So this has been deprecated for clarity in favour of more
explicitly named methods."
According to the Javadoc of scheduleBuild2() the unit of quietPeriod is
seconds whereas getTime() returned seconds. This looks like a bug.
Therefore now using getTimeInSeconds() instead of getTimeInMillis().
=> Fix TimeDuration#getTime() call

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
@jglick is there any blocker to make it non-final?
`super.init()` is not final but this override blocks ability to make aditional initialisations right after job was moved and has new `parent, name`. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/cloudbees-folder-plugin/121)
=> Allow implementations do initialisation additions

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
ComputedFolder doesn't provide a function to remove a trigger.
* Entry 1: Feature, Provide a function to remove an exists trigger
@fcojfernandez
=> Add function to remove trigger

src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/configure-details.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/orphanedItemStrategyDescription.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/orphanedItemStrategyDescription.properties
The description and comments on the ticket suggests that it is only a misunderstanding on what the orphaned item strategy is actually about, so adding a generic explanation that can be changed by implementations for a more context specific explanation.
See [JENKINS-48452](https://issues.jenkins-ci.org/browse/JENKINS-48452).
See downstream PR for screenshots: https://github.com/jenkinsci/branch-api-plugin/pull/157 
* Explain the orphaned item strategy
* UI Text change only.
@fcojfernandez
@abayer 
@dwnusbaum 
@bitwiseman
=> [JENKINS-48452] Explain the orphaned item strategy.

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration.java, src/main/resources/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration/config.jelly, src/test/java/com/cloudbees/hudson/plugins/folder/ConfigurationAsCodeTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/resources/com/cloudbees/hudson/plugins/folder/configuration-as-code.yaml
See [JENKINS-58282](https://issues.jenkins-ci.org/browse/JENKINS-58282). Large instances are awfully impacted by performances issues related to health metrics. As a workaround, the health metrics can be removed but every time a new folder is created, it has all folder health metrics configured and there is no way around this. This feature is meant to help administrator to control this.
* Ability to configure default folder health metrics
@fcojfernandez
=> [JENKINS-58282] Ability to configure default folder health metrics

src/main/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfigurationTest.java
See [JENKINS-60393](https://issues.jenkins-ci.org/browse/JENKINS-60393): the configuration of the defaults in the constructor of the GlobalConfiguration may cause the loading to fail on startup in some cases
* Ensure all plugin are loaded before setting global defaults
@fcojfernandez @rsandell
=> [JENKINS-60393] Ensure all plugins are loaded to configure the defaults

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
This adds an API to check if there are visible items.
See jenkinsci/branch-api-plugin#173 for potential use where this can improve performance for the downstream consumer by reducing number of `hasPermission` checks done to its bare minimum instead of checking against every item.
* Developer: Add hasVisibleItems API
@fcojfernandez
=> Add hasVisibleItems API

Jenkinsfile, pom.xml
Work in progress to make sure this plugin is constantly checked both building with JDK8 and JDK11.
This goes with the Jenkins Java 11 General Availability announcement made back in March, and we're making a pass to check plugins are looking good on a JDK11.
([to understand the Jenkinsfile content](https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime))
=> [WIP] Java 11 readiness: build both on JDK8 and JDK11

pom.xml
We have a CI failure on a bom PR (https://github.com/jenkinsci/bom/pull/172) that seems to be caused by an old credentials plugin dep here
https://ci.jenkins.io/blue/organizations/jenkins/Tools%2Fbom/detail/PR-172/11/tests
Could we get a release for the bom too pretty please, this is our last failure on bumping jcasc in the bom
=> Bump credentials plugin for bom

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See [JENKINS-60900](https://issues.jenkins-ci.org/browse/JENKINS-60900): The controls for the "Disable" feature are not displayed.
* Display Enable / Disable buttons in a Folder's page if it supports it
@fcojfernandez
=> [JENKINS-60900] Fix enable/disable controls display

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Downstream of jenkinsci/jenkins#4469
* Entry 1: Developer, predicate form of getItems API
* ...
@fcojfernandez
=> Predicate form of getItems() API

src/main/resources/com/cloudbees/hudson/plugins/folder/Messages_fr.properties
Signed-off-by: Jean-Baptiste Le Duigou <jb.leduigou@gmail.com>
See [JENKINS-61489](https://issues.jenkins-ci.org/browse/JENKINS-61489).
@fcojfernandez
=> Adding french translation for message bundle

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
Will likely help with https://github.com/jenkinsci/bom/pull/225
We're getting failures on cloudbees-folder for some reason with PCT and updated jcasc =/ 
98% of users who updated to the last 2 releases will be able to use this minimum version:
http://stats.jenkins.io/pluginversions/cloudbees-folder.html
* ...
@fcojfernandez
=> Bump core and parent

src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfigurationTest.java
1. `FolderTest.shouldHaveHealthMetricConfiguredGloballyOnCreation`: is checking [something](https://github.com/jenkinsci/cloudbees-folder-plugin/blob/2b9443b5c5d72030a92f59e8843c8948022830b5/src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java#L420) which is not necessarily true (it depends on [this condition](https://github.com/jenkinsci/cloudbees-folder-plugin/blob/ae00f49fc0c6183983d67c799772fd8b9adc0840/src/main/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration.java#L50)). So I suspect there is a `FolderHealthMetricDescriptor` in the classpath (from some other plugin) which is returning `null` on `FolderHealthMetricDescriptor#createDefault` (which is fine).
2. `AbstractFolderConfigurationTest#shouldBeAbleToRemoveHealthMetricConfiguredGlobally`: …
=> This tests are failing when running on the PCT

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/DeletingChildrenException.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See [JENKINS-62632](https://issues.jenkins-ci.org/browse/JENKINS-62632).
* Entry 1: Process and try to delete all children before actually raising the exceptions for those who could not be deleted.
@fcojfernandez
=> [JENKINS-62632] Process all children before raising exceptions

src/main/java/com/cloudbees/hudson/plugins/folder/computed/DefaultOrphanedItemStrategy.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ConfigurationAsCodeTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder2Test.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/EventOutputStreamsTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ThrottleComputationQueueTaskDispatcherTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfigurationTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
* used diamond operator, 
* some try with resources
* remove superflous throws and 
* fixed some deprecation warnings (most of junit deprecation of assertThrows)
* Internal: Refactorings
@fcojfernandez
=> use diamond operator, remove superflous throws and fixed some deprecation warnings

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
See [JENKINS-63312](https://issues.jenkins-ci.org/browse/JENKINS-63312).
* Entry 1: Fix possible memory leak (`FolderComputation` chained to previous `FolderComputation`, etc.)
@fcojfernandez
=> [JENKINS-63312] avoid unnecessary chaining of FolderComputations

src/main/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderSystemPropertyTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfigurationTest.java
See [JENKINS-63836](https://issues.jenkins-ci.org/browse/JENKINS-63836).
* [JENKINS-63836](https://issues.jenkins-ci.org/browse/JENKINS-63836) : Not add heath metrics by default in the Global Configuration
@fcojfernandez
=> [JENKINS-63836] Not add heath metrics by default in the Global Configuration

.mvn/extensions.xml, Jenkinsfile, pom.xml
See https://github.com/jenkinsci/cloudbees-folder-plugin/pull/165#issuecomment-724716790. Supersedes #166, #167, and #168.
=> Refresh POM and dependencies

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder/configure-details.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/computed/FolderComputation/index.jelly, src/main/resources/lib/folder/blockWrapper.jelly
See [JENKINS-64069](https://issues.jenkins-ci.org/browse/JENKINS-64069).
As well as branch-api fixs this plugin needs updates otherwise it breaks branch-api
* Entry 1: JENKINS-64069, Add compatibility with Jenkins 2.264
* ...
@fcojfernandez
=> JENKINS-64069 Fix plugin / branch-api on 2.264

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
Uses more legible cause chaining. Noticed while working on https://github.com/jenkinsci/branch-api-plugin/pull/220.
=> Use Functions.printStackTrace

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
I noticed this problem on an organization folder, but I assume the problem is the same with any folder that can be disabled.
* Fix roundtrip of `disabled` field for folders
@fcojfernandez
=> Fix roundrip of the `disabled` field on folders

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See [JENKINS-66168](https://issues.jenkins.io/browse/JENKINS-66168)
* Fix "Enable|Disable Multibranch Pipeline" button from non-primary views of Folders.
=> [JENKINS-66168] Fix the Disable/Enable button for non primary views

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
See jenkinsci/jenkins#5569. Migrates from `hudson.util.CaseInsensitiveComparator` to Java's native `String.CASE_INSENSITIVE_ORDER`.
=> Migrate from `hudson.util.CaseInsensitiveComparator` to Java `String.CASE_INSENSITIVE_ORDER`

Jenkinsfile
This enables JDK11 CI build for this plugin.
* Entry 1: Internal: enable CI build using JDK11
=> chore: Enable JDK11 build

src/main/resources/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger/help-interval.html
See [JENKINS-55429](https://issues.jenkins-ci.org/browse/JENKINS-55429).  Having recently run into this same issue, I took the step requested by Daniel Spilker and created this PR against the Folder plugin to improve the documentation around the expected value for `interval`.
* Document sample value for `periodicFolderTrigger / interval`
@fcojfernandez
=> document sample value for interval

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
See [JENKINS-67753](https://issues.jenkins.io/browse/JENKINS-67753).
The change proposed exchanges the icon for unbuild items from "grey" to "notbuilt" allowing newer Jenkins versions to override it properly and display the modernized "notbuilt" sprite if available, and a grey ball on older versions:
* ...
=> [JENKINS-67753] Use "notbuilt" icon instead of grey to display the build status

pom.xml
fixes #210 by updating to a version of Jenkins that provides spotbugs annotations to prevent the compilation issue that occurs in the newer plugin pom
=> Bump plugin from 4.21 to 4.34

src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
Found when running `mvn clean verify -Dtest=com.cloudbees.hudson.plugins.folder.computed.ComputedFolderTest -Djenkins-test-harness.version=1721.v385389722736 '-DargLine=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED'` on Java 17 as in jenkinsci/bom#935. The problem is that the test is trying to serialize a latch, which is not a realistic production use case. This PR  makes the latch transient so XStream doesn't try to serialize it. The test doesn't need to restart Jenkins, so it doesn't need this field to be serialized. And this gets the test to pass on Java 17.
```
java.io.IOException: java.lang.RuntimeException: Failed to serialize …
```
=> Do not serialize `CountDownLatch`

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/main/webapp/images/svgs/folder-store.svg
See [JENKINS-68674](https://issues.jenkins-ci.org/browse/JENKINS-68674).
Before this PR, the icon for the folder credentials in the crumb bar was missing. Now with the change, the icon is back:
* Entry 1: Issue, Icon for folder credentials store has been updated to match credentials plugin change
=> Icon for folder credentials store is gone from credentials plugin

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/tasks-top.jelly
Tiny PR to remove the hierarchal sidebar link (Up), following the changes in https://github.com/jenkinsci/jenkins/pull/6907 which does the same for the freestyle project type.
---
* The hierarchal sidebar link has been removed
=> Remove the hierarchal sidebar link

src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java
`folder-store.svg` was moved from the credentials plugin to the folder plugin, the old reference displays a broken image:
The change proposed addresses the issue and restores the icon:
=> Restore broken folder credentials icon

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly
Hello, HacktoberFest is here ([Content Security Policy: smooth introduction Topic](https://issues.jenkins.io/browse/JENKINS-60865))
See [JENKINS-69914](https://issues.jenkins.io/browse/JENKINS-69914).
[Content-Security-Policy Compatibility documentation](https://www.jenkins.io/doc/developer/security/csp/#legacy-javascript-checkurl-validation)
Manual testing recoding:
https://user-images.githubusercontent.com/47667812/197193449-126ba19b-fd61-4150-884f-b665da66c3e9.mov
=> [JENKINS-69914] Remove overcomplicated `checkUrl` (CSP compatibility)

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly
This PR adds missing breadcrumbs to the job configuration page.
**Before**:
**After**:
=> Add missing breadcrumbs to job configuration

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly
This PR aligns the sidepanel with the mainpanel, according to recent job configuration view changes and the overall layout known from other job types, e.g., pipelines.
**Before**:
**After**:
=> Realign sidepanel with mainpanel through app bars

Jenkinsfile, pom.xml
Test with Java 21
==
Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Testing done
===
Confirmed tests pass with Java 21 after upgrading to a recent parent POM.
=> Test with Java 21 and parent pom update

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
=> jep-227 downstream usage

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
Downstream of https://github.com/jenkinsci/jenkins/pull/8544, available in our baseline as of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/356. Useful in CloudBees CI, but seems appropriate here anyway so that `getDataFile` is used in a more encapsulated way. (It cannot be `private` since `BranchIndexing` overrides it.)
=> Make `FolderComputation` implement `Loadable`

src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
See [JENKINS-72611](https://issues.jenkins.io/browse/JENKINS-72611).
* Forbid updating credentials ID
=> [JENKINS-72611] Forbid updating credentials ID

src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
Reverts jenkinsci/cloudbees-folder-plugin#366
Jenkins throws an error when updating credentials that are not ID credentials
=> Revert "[JENKINS-72611] Forbid updating credentials ID"

src/main/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProvider.java, src/test/java/com/cloudbees/hudson/plugins/folder/properties/FolderCredentialsProviderTest.java
See [JENKINS-72611](https://issues.jenkins.io/browse/JENKINS-72611).
https://github.com/jenkinsci/cloudbees-folder-plugin/pull/366 caused regressions, so this is another take.
* Forbid updating credentials ID for `IdCredentials`
=> [JENKINS-72611] Forbid updating credentials ID for `IdCredentials`

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java, src/test/java/com/cloudbees/hudson/plugins/folder/FolderTest.java
Reverts the refactoring portions of #372, which proved to cause PCT regressions, keeping only the simpler and safer #367. Refactoring to reduce duplication would still be nice but can be done later.
=> Revert refactoring of `ChildNameGenerator`

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java
Follow up to @mawinter69 changes in core (https://github.com/jenkinsci/jenkins/pull/9127). This PR uses the folder symbol now that the 'New item' page supports displaying them.
**Before**
**After**
* Use symbol for folder icon
=> Use symbol for folder icon

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration.java
See [JENKINS-73086](https://issues.jenkins-ci.org/browse/JENKINS-73086).
* ...
=> [JENKINS-73086] Allow users with Overall/Manage permission to configure global default folder settings

pom.xml, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
Remove disable button to match other job type since 2.460
I can open an Jira ticket if needed
* Remove disable button to match other job type since 2.460
=> Remove disable button to match other job type since 2.460

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
While testing some scenarios involving job deletion in CloudBees CI, we found some anomalous events caused by a save event on `config.xml` of the parent folder. This makes no apparent sense, because the folder is not being modified.
=> Gratuitous `save` from `AbstractFolder.onDeleted/onRenamed`

Jenkinsfile, pom.xml
Closes #438.
Closes #431.
This bumps the Jenkins version required for the plugin from 2.462.1 to 2.479.1, moving to build the plugin with Java 17 minimum.
I ran the tests locally but didn't expect any issues as the plugin is already built and tested on Java 17 and with this version of Jenkins in the BOM PCT execution.
* Internal: Bump Jenkins required version from 2.462.1 to 2.479.1
=> Bump Jenkins version from 2.462.1 to 2.479.1

src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java
https://github.com/jenkinsci/branch-api-plugin/pull/468 but on the base class that defines `isBuildable`
See [JENKINS-73425](https://issues.jenkins.io/browse/JENKINS-73425).
Obsoletes https://github.com/jenkinsci/branch-api-plugin/pull/468 (untested)
* Expose `buildable` for ComputedFolders to the REST API
=> [JENKINS-72958] expose buildable property to API

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/sidepanel.jelly
Not observed as such, but seems possible from code inspection. See https://github.com/jenkinsci/jenkins/pull/10023.
=> Defend against null `AbstractFolder.primaryView`

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See [JENKINS-73930](https://issues.jenkins.io/browse/JENKINS-73930). Amend 
The button was removed from https://github.com/jenkinsci/cloudbees-folder-plugin/pull/419. But along with the warning. It is not obvious anymore when a folder is disabled.
Before:
After:
* Re-instaore the Disabled warning when a Folder is disabled
=> [JENKINS-73930] Put back the disabled warning

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
Part of https://github.com/jenkinsci/jenkins/pull/10049 but can be merged interdependently 
* ...
=> Add icons for search

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
[JENKINS-74990](https://issues.jenkins.io/browse/JENKINS-74990) notes that when a folder definition includes the XML:
```
<icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.1200.v4b_a_3da_2eb_db_4">
<owner class="com.cloudbees.hudson.plugins.folder.Folder" reference="../.."/>
</icon>
```
then the 6.971.v9a_984fd08864 release of the plugin reports a stack overflow.
Revert the change so that there is enough time for diagnosis without the pressure of users reporting and diagnosing bugs.
Change has no tests because I wanted to implement a quick solution so that users won't be affected.
This reverts commit c9fe2ab306a977d2946c6d44724fc062fd5391b7.
Confirmed that the issue is visible without this change and is resolved with this change.  Details in …
=> [JENKINS-74990] Prevent stack overflow / Revert 'Add icons for search'

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
I noticed `OldDataMonitor` showing _Scan Repository_ under **Name** for a `BranchIndexing`, which was not very helpful; I had to use the script console to find the exact `indexing.xml` affected. https://github.com/jenkinsci/jenkins/blob/810c4b41613aafe0e0ac491b8e6013d92ed1ea26/core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage.jelly#L51 is the logic here (called reflectively, alas, which is why this does not `@Override` anything).
Tested interactively as part of a bug fix in CloudBees CI.
=> Define `FolderComputation.fullName` for use from `OldDataMonitor`

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderProperty.java, src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/Folder.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderAddFilter.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderIcon.java, src/main/java/com/cloudbees/hudson/plugins/folder/FolderPropertyDescriptor.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PseudoRun.java, src/main/java/com/cloudbees/hudson/plugins/folder/config/AbstractFolderConfiguration.java, src/main/java/com/cloudbees/hudson/plugins/folder/icons/StockFolderIcon.java, src/main/java/com/cloudbees/hudson/plugins/folder/relocate/DefaultRelocationUI.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolderTest.java
See jenkinsci/jenkins#9672.
- Passing CI build
- Tested in context in `branch-api` and `matrix-auth` before and after migrating those plugins to EE 9
- ATH (weekly and LTS): passing
- BOM (weekly): passing
=> Migrate from EE 8 to EE 9

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly
to be in sync with the configure screen of jobs
I think this is helpful especially for multibranch or org folders that have longer config screens.
* Make sidepanel sticky in folder configuration
* ...
=> make side-panel sticky on configure screen

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java
PR #376 caused every child to be recreated on reload, whereas the intent is to retain the object identity.
cf. https://github.com/jenkinsci/cloudbees-folder-plugin/pull/376#discussion_r2035617683 (thank you @basil)
* Fix a regression causing all children to be recreated on folder reload when using a `NameMangler`
=> Retain child item identity when using a `NameMangler`

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java
`ChildNameGenerator#CHILD_NAME_FILE` introduces unnecessary complexity and has been at the scene of several concurrency issues, so we would like to eventually remove it. But it is not completely clear if it is still needed. I stepped through a few scenarios in the debugger in `cloudbees-folder`, `branch-api`, and `workflow-multibranch`, and I couldn't find a case where it was needed. But my confidence is low that I have fully understood the problem.
If there are no calls to `readItemName`, then it is pointless to write the item name and we can also remove all calls to `writeItemName`. So what would it take to remove all calls to `readItemName`? This PR computes the item name a new way, without relying on `readItemName`, and then calls `readItemName` to confirm that the results are the …
=> Prepare to eventually remove `ChildNameGenerator#CHILD_NAME_FILE`

src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorAltTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorRecTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java, src/test/java/com/cloudbees/hudson/plugins/folder/computed/ComputedFolder2Test.java
Migrate from deprecated functionality to non-deprecated equivalent.
N/A
=> Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java
As with #484, I am pretty sure that this is dead code, and I would like to delete it, but I am not entirely sure I have understood the problem. So planning to deploy this to Jenkins users with an assertion that we are never hitting this code path, and if nobody complains that the assertion is firing then I will feel more confident that this code can be deleted.
Will run BOM.
=> Prepare for eventual removal of `ChildNameGenerator#ensureItemDirectory`

src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java
The use of this annotation dates back to #86, but the bridge method is not actually present today because of the lack of `bridge-method-injector` during the build process. Since the intervening 8 years have clearly demonstrated that the bridge method is not actually needed, remove the useless annotation rather than adding `bridge-method-injector` to the build.
Dumped the bytecode of the class with `javap` before and after this change and verified it was the same (i.e., no bridge method both before and after, as expected).
N/A
=> Remove useless annotation

pom.xml, src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PeriodicFolderTrigger.java, src/main/java/com/cloudbees/hudson/plugins/folder/computed/PseudoRun.java, src/test/java/com/cloudbees/hudson/plugins/folder/ChildNameGeneratorTest.java
To be able to remove commons-lang from core all direct and indirect usages must be replaced with commons-lang3 or native Java
- use XS_DATETIME_FORMATTER2 instead of deprecated XS_DATETIME_FORMATTER from core
- replaced commons-lang with native Java
* remove usages of commons-lang from core
=> remove usages of commons-lang from core

src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java, src/main/java/com/cloudbees/hudson/plugins/folder/ChildNameGenerator.java
Completes the work started in #487 by completely removing any references to `ChildNameGenerator#ensureItemDirectory`. Nobody ever complained about us hitting the assertion, so this must be dead code that can be safely removed.
=> Remove `ChildNameGenerator#ensureItemDirectory`

src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.jelly, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top.properties, src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/view-index-top_ja.properties
Comparing the view of a folder vs. job I noticed some minor differences this PR aims to fix by adapting the definitions in `AbstractFolder/view-index-top.jelly` to the [core](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/Job/index.jelly).
Most notable changes:
* same size of text and icon
* same display of the "full name" in case a folder is nested
See the following screenshots for comparissions:
| Job | Folder |
|-|-|
| ![grafik](https://github.com/user-attachments/assets/6aea06d6-11ae-45f4-9fed-8c9e96655f4f) | ![grafik](https://github.com/user-attachments/assets/cc2afd32-f990-45fd-93fd-ed44a7842097) | 
| ![grafik](https://github.com/user-attachments/assets/8ef7da3b-0d24-4e63-9fad-dceceb264e2d) | …
=> Folder view matches look of job view
